---
- name: install java 8
  apt:
    name: openjdk-8-jre-headless
    state: present
    force: yes
    update_cache: yes
  become: true

- name: add JAVA_HOME path
  become: true
  lineinfile:
    path: /etc/environment
    regexp: '^JAVA_HOME='
    line: JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-amd64"
    state: present
