---
# https://clickhouse.com/docs/ru/getting-started/install/#install-from-deb-packages
- name: Install supplementary packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - dirmngr
    update_cache: yes
  become: true

- name: Add APT key to ClickHouse
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: "E0C56BD4"
    state: present
  become: true

- name: Add repo for ClickHouse
  apt_repository:
    repo: "deb https://repo.clickhouse.tech/deb/stable/ main/"
    filename: "/etc/apt/sources.list.d/clickhouse.list"
    state: present
  become: true


- name: Install ClickHouse
  apt:
    pkg:
      - clickhouse-server
      - clickhouse-client
  notify: Enable ClickHouse

