---
- name: Enable ClickHouse
  systemd:
    name: clickhouse-server
    enabled: yes
    state: started
    daemon_reload: yes

- name: Restart ClickHouse
  systemd:
    name: clickhouse-server
    state: restarted
